import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Sidebar } from "@/components/Sidebar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";
import { LocationProvider } from "@/components/LocationContext";

const alexandria = Alexandria({
  subsets: ["latin", "arabic"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as "ar" | "en")) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body className={`${alexandria.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <LocationProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="flex bg-background min-h-screen w-full">
                <Sidebar className="max-lg:hidden" />
                <div
                  className="flex-1 lg:p-4 w-full"
                  style={{
                    minHeight: "calc(100vh - 280px)",
                  }}
                >
                  {children}
                </div>
              </div>
              <Toaster position="top-center" />
            </ThemeProvider>
          </LocationProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
